export const LICENSE_LIST_REQUEST = "LICENSE_LIST_REQUEST";
export const LICENSE_LIST_SUCCESS = "LICENSE_LIST_SUCCESS";
export const LICENSE_LIST_FAIL = "LICENSE_LIST_FAIL";

export const LICENSE_EDIT_REQUEST = "LICENSE_EDIT_REQUEST";
export const LICENSE_EDIT_SUCCESS = "LICENSE_EDIT_SUCCESS";
export const LICENSE_EDIT_FAIL = "LICENSE_EDIT_FAIL";

export const LICENSE_DELETE_REQUEST = "LICENSE_DELETE_REQUEST";
export const LICENSE_DELETE_SUCCESS = "LICENSE_DELETE_SUCCESS";
export const LICENSE_DELETE_FAIL = "LICENSE_DELETE_FAIL";

export const LICENSE_DOWNLOAD_REQUEST = "LICENSE_DOWNLOAD_REQUEST";
export const LICENSE_DOWNLOAD_SUCCESS = "LICENSE_DOWNLOAD_SUCCESS";
export const LICENSE_DOWNLOAD_FAIL = "LICENSE_DOWNLOAD_FAIL";

export const LICENSE_CREATE_REQUEST = "LICENSE_CREATE_REQUEST";
export const LICENSE_CREATE_SUCCESS = "LICENSE_CREATE_SUCCESS";
export const LICENSE_CREATE_FAIL = "LICENSE_CREATE_FAIL";
export const LICENSE_CREATE_RESET = "LICENSE_CREATE_RESET";

export const LICENSE_UPDATE_REQUEST = "LICENSE_UPDATE_REQUEST";
export const LICENSE_UPDATE_SUCCESS = "LICENSE_UPDATE_SUCCESS";
export const LICENSE_UPDATE_FAIL = "LICENSE_UPDATE_FAIL";
export const LICENSE_UPDATE_RESET = "LICENSE_UPDATE_RESET";
